<a href="https://colab.research.google.com/github/alexandergribenchenko/Data_Science_Toolkit/blob/main/Sklearn_Transformers/DS_TS_EX_01_Customized_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn import set_config

In [56]:
mi_pipeline=Pipeline(steps=[("mi_escalador",StandardScaler(with_mean=False)),
                     ("mi_clasificador",LogisticRegression())])

In [57]:
set_config(display="diagram")
mi_pipeline

Pipeline(steps=[('mi_escalador', StandardScaler(with_mean=False)),
                ('mi_clasificador', LogisticRegression())])

In [58]:
set_config(display="text")
mi_pipeline

Pipeline(steps=[('mi_escalador', StandardScaler(with_mean=False)),
                ('mi_clasificador', LogisticRegression())])

In [59]:
mi_pipeline.get_params()

{'memory': None,
 'steps': [('mi_escalador', StandardScaler(with_mean=False)),
  ('mi_clasificador', LogisticRegression())],
 'verbose': False,
 'mi_escalador': StandardScaler(with_mean=False),
 'mi_clasificador': LogisticRegression(),
 'mi_escalador__copy': True,
 'mi_escalador__with_mean': False,
 'mi_escalador__with_std': True,
 'mi_clasificador__C': 1.0,
 'mi_clasificador__class_weight': None,
 'mi_clasificador__dual': False,
 'mi_clasificador__fit_intercept': True,
 'mi_clasificador__intercept_scaling': 1,
 'mi_clasificador__l1_ratio': None,
 'mi_clasificador__max_iter': 100,
 'mi_clasificador__multi_class': 'auto',
 'mi_clasificador__n_jobs': None,
 'mi_clasificador__penalty': 'l2',
 'mi_clasificador__random_state': None,
 'mi_clasificador__solver': 'lbfgs',
 'mi_clasificador__tol': 0.0001,
 'mi_clasificador__verbose': 0,
 'mi_clasificador__warm_start': False}

In [60]:
type(mi_pipeline.get_params())

dict

In [65]:
mi_pipeline.set_params({'mi_escalador__with_mean'=True, 'mi_escalador__copy': True})

SyntaxError: ignored

In [62]:
mi_pipeline.get_params()

{'memory': None,
 'steps': [('mi_escalador', StandardScaler()),
  ('mi_clasificador', LogisticRegression())],
 'verbose': False,
 'mi_escalador': StandardScaler(),
 'mi_clasificador': LogisticRegression(),
 'mi_escalador__copy': True,
 'mi_escalador__with_mean': True,
 'mi_escalador__with_std': True,
 'mi_clasificador__C': 1.0,
 'mi_clasificador__class_weight': None,
 'mi_clasificador__dual': False,
 'mi_clasificador__fit_intercept': True,
 'mi_clasificador__intercept_scaling': 1,
 'mi_clasificador__l1_ratio': None,
 'mi_clasificador__max_iter': 100,
 'mi_clasificador__multi_class': 'auto',
 'mi_clasificador__n_jobs': None,
 'mi_clasificador__penalty': 'l2',
 'mi_clasificador__random_state': None,
 'mi_clasificador__solver': 'lbfgs',
 'mi_clasificador__tol': 0.0001,
 'mi_clasificador__verbose': 0,
 'mi_clasificador__warm_start': False}

In [78]:
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
class MultiplyColumns(BaseEstimator, TransformerMixin):
    def __init__(self, by=1, columns=None):
        self.by = by
        self.columns = columns
    
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        cols_to_transform = list(X.columns)
        if self.columns:
            cols_to_transform = self.columns
        X[cols_to_transform] = X[cols_to_transform] * self.by
        return X
# Use Custom Transformer
df = pd.DataFrame({"a": [1, -2, 3], "b": [-4, 5, 6], "c": [-7, -8, 9]})
pipe = Pipeline(steps=[("multiply_cols_by_3", MultiplyColumns(3, columns=["a", "c"])),
                       ("multiply_cols_by_5", MultiplyColumns(5, columns=["b", "c"]))]
              )
transformed_df = pipe.fit_transform(df)
print(df)

   a   b    c
0  3 -20 -105
1 -6  25 -120
2  9  30  135


In [79]:
pipe.get_params()

{'memory': None,
 'steps': [('multiply_cols_by_3', MultiplyColumns(by=3, columns=['a', 'c'])),
  ('multiply_cols_by_5', MultiplyColumns(by=5, columns=['b', 'c']))],
 'verbose': False,
 'multiply_cols_by_3': MultiplyColumns(by=3, columns=['a', 'c']),
 'multiply_cols_by_5': MultiplyColumns(by=5, columns=['b', 'c']),
 'multiply_cols_by_3__by': 3,
 'multiply_cols_by_3__columns': ['a', 'c'],
 'multiply_cols_by_5__by': 5,
 'multiply_cols_by_5__columns': ['b', 'c']}

In [80]:
set_config(display="diagram")
pipe

Pipeline(steps=[('multiply_cols_by_3',
                 MultiplyColumns(by=3, columns=['a', 'c'])),
                ('multiply_cols_by_5',
                 MultiplyColumns(by=5, columns=['b', 'c']))])

In [72]:
pipe.set_params(multiply_cols_by_3__columns=['a', 'b'])

Pipeline(steps=[('multiply_cols_by_3',
                 MultiplyColumns(by=3, columns=['a', 'b']))])

In [74]:
set_config(display="diagram")
pipe

Pipeline(steps=[('multiply_cols_by_3',
                 MultiplyColumns(by=3, columns=['a', 'b']))])

In [81]:
set_config(display="text")
pipe

Pipeline(steps=[('multiply_cols_by_3',
                 MultiplyColumns(by=3, columns=['a', 'c'])),
                ('multiply_cols_by_5',
                 MultiplyColumns(by=5, columns=['b', 'c']))])

In [82]:
pipe.set_params(multiply_cols_by_5__columns=['b', 'a'])

Pipeline(steps=[('multiply_cols_by_3',
                 MultiplyColumns(by=3, columns=['a', 'c'])),
                ('multiply_cols_by_5',
                 MultiplyColumns(by=5, columns=['b', 'a']))])

In [83]:
df

a   b    c
0  3 -20 -105
1 -6  25 -120
2  9  30  135

In [85]:
transformed_df = pipe.transform(df)
transformed_df

a    b     c
0   675 -500  -945
1 -1350  625 -1080
2  2025  750  1215

In [ ]:
##creating a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [ ]:
X.shape

(1000, 20)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
X_train

array([[-0.04273089,  0.62733708,  0.73184038, ...,  0.3161405 ,
        -0.69896992,  1.64448249],
       [ 1.21701213,  0.91859103, -0.61566102, ...,  0.47032105,
        -0.69394003,  0.78492765],
       [ 0.12829608,  0.66924697, -0.02577067, ..., -0.11017591,
         1.56790864, -0.03463564],
       ...,
       [-1.00451509, -1.5852426 , -0.66870921, ...,  0.32671781,
         0.49407756,  0.00962666],
       [ 0.51858508,  1.74562552,  0.45465545, ...,  1.11683758,
         0.35944106, -0.13306576],
       [ 0.16536114, -0.98364616,  1.02300279, ...,  2.03273883,
         0.66776423, -0.47030654]])

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
y_pred=pipe.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

## Example 2
Displaying a pipeline with standard scaler, dimesnionality reduction and then estimator

In [ ]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [ ]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]

In [ ]:
pipe2=Pipeline(steps)

In [ ]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [ ]:
pipe2.predict(X_test)

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

## Complex examples of columns transformer

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
## numerical processing pipeline
import numpy as np
numeric_processor=Pipeline(
    steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
          ("scaler",StandardScaler())]

)

In [ ]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [ ]:
##categorical procesing pipeline

In [ ]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]

)

In [ ]:
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [ ]:
## combine processing technqiues
from sklearn.compose import ColumnTransformer

In [ ]:
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]


)

In [ ]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [ ]:
from sklearn.pipeline import make_pipeline

In [ ]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [ ]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])